### PR TITLE
Fixed currentUpdatedHandlerId variable appearing multiple times in several build units.

### PR DESCRIPTION
**Pull request by kasedy**
When global static variable is declared in a header file it creates independent copies in every build unit where the header is included. That may cause issues in future when two variables generate the same handler_id. Moved its declaration inside StateUpdateHandlerInfo struct and initialization inside StatefulService.cpp. It will ensure we have only one variable and unique handler ids.

### CODE REVIEW

**Comment by rjwats** [comment]
Cool thanks for the guidance there. Out of interest, why do we need to explicitily initialize it to zero?

**Comment by kasedy** [comment]
I believe that "Explicit is better than implicit." It is one of Python Zen (Run in command line: python -c "import this") principals.

**Comment by rjwats** [comment]
OK thx - I was wondering if there was somthing special about static instantiation that I didn't understand.

I guess it's a subjective thing - the "improving clarity" vs "reducing noise" argument. The framework should probably choose a single approach because consistency is way more important. I think on the subjective side, I perfer letting the language do it's thing and go for implisit where possible.

I'll do a pass over the code for consistancy at some point... thx for this fix.

**Comment by rjwats** [comment]
Ah, it's gone :) Was this not a good change?

**Pull request merged**
