### PR TITLE
Rename Experiments

### PR DESCRIPTION
**Pull request by rjwats**
Experimenting with renames, and splitting "core", and "util" code from "framework" code for clarity.

Introducing separate classes for Http GET/POST, Websocket Rx/Tx and Mqtt Pub/Sub.

### CODE REVIEW

**Comment by rjwats** [comment]
@kasedy

Some of the changes discussed in the other branch. I've not finished updating README.md.

**Comment by kasedy** [comment]
PlatformIo suggests (teadme.txt in lib) to place the source code of each library in separate directory. Therefore if we still have a single library, "core" and "util" directories should be inside "framework". If it is three individual libraries we should come up with original names. I personally have personal /lib/util library with bunch of helpful functions that I copy over all my projects. I could be not the only one.

**Comment by rjwats** [comment]
I've moved the framework code back into a single lib directory for now. I like the idea of separation of class types, however I couldn't find a solution I was happy with. [LDF](https://docs.platformio.org/en/latest/librarymanager/ldf.html) is more complicated than I remember it.

Think there are so many changes in the PR that this may as well be parked for another PR once master is caught up any way. I'm going to merge these changes back into the feature branch, feature freese, and work on the README, bug fixes and tidyups before getting this back in so we can work on the other stuff we've discussed. Feels like the big changes are nearly done.

**Comment by proddy** [comment]
the LDF is tricky but it's possible to have separate source file folders and get platformio to build it successfully, using parameters in `platformio.ini` like for example `build_flags = -I./src/Common` and `lib_ldf_mode=chain+`. I can take a look if you want.

**Pull request merged**
