### PR TITLE
Upgrade e32 4.3.0

### PR DESCRIPTION
**Pull request by rjwats**

### CODE REVIEW

**Comment by rjwats** [comment]
Is anyone able to give this a test/review for me?

**Comment by proddy** [comment]
<RouterTabs> is missing the children property?

**Comment by rjwats** [comment]
Humm.. shouldn't be, are you getting an error?

image

**Comment by rjwats** [comment]
try an "npm ci" - could be a deps issue?

**Comment by proddy** [comment]
> try an "npm ci" - could be a deps issue?

youe repo works just fine, the problem on my side on my project. If apply the same changes for react18 to my fork I get

Screenshot 2022-05-21 174628

**Comment by rjwats** [comment]
Oh right, this is a change in React 18:

FC used to be:

image

and now is:

image

So children must be declared, there's a helper you can use to mix these into existing interfaces, or you can do this like i'm doing in my PR with a utility type your props interfaces can extend from :)

**Comment by proddy** [comment]
BTW I also modifed `/src/index.tsx` to

```ts
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';

import App from './App';

const root = createRoot(document.getElementById('root') as HTMLElement);

root.render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>
);
```

as per https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

**Comment by rjwats** [comment]
ah, yes, thanks :)

**Pull request merged**
