### PR TITLE
Display SDK version and Heap fragmentation at System info page. 

### PR DESCRIPTION
**Pull request by kasedy**

### CODE REVIEW

**Comment by kasedy** [comment]
JsonDeserializer may return false to prevent unnecessary update propagation in case if settings object was not change.

**Comment by rjwats** [comment]
The "like" icon seems like a strange choice for the SDK version, can I suggest that "Build" would be a better icon:

`import BuildIcon from '@material-ui/icons/Build';`

Maybe "gradient" would be better fragmentation too:

 `import GradientIcon from '@material-ui/icons/Gradient';`

**Comment by rjwats** [comment]
I like the idea of making the update callback return a boolean to indicate whether it made an update, that seems very sensible to me. I'm really not so sure about deserializer doing the same. Shall we add it to the update callback only for now? It supports the use-case and keeps some noise out of the code.

My thinking is that a "deserializer" shouldn't be making business logic decisions, highlighted by the fact our internal deserializers simply return true.

I need to spend some time using the framework, whenever I do I discover things I wish it did, or things which are tricky, this is probably an example of that.

**Comment by kasedy** [comment]
Updated icons.

I believe we should update both (callback and deserializer). Previously deserializer was inside update callback. It is a particular implementation of callback for json. It knows if settings was not updated and should notify StatefulService. 

I'm trying to address "ERROR: Too many messages queued" problem. It happens when web socket generates a lot of messages that later get redirected to mqtt. It causes AsyncSocket message queue overflow. If some part the system generates identical messages we should not forward them.

**Comment by rjwats** [comment]
> I believe we should update both (callback and deserializer). Previously deserializer was inside update callback. It is a particular implementation of callback for json. It knows if settings was not updated and should notify StatefulService.

Whatever change we implement here will need documenting in the README before it can go to master. It might be this change can allow for the removal the non propogating functions. I'm not sure about this still and want to look at this properly, might find time tonight.

Meanwhile, the heap-frag changes look good to go, so if you want to raise those in a seperate PR we can get them in.

> I'm trying to address "ERROR: Too many messages queued" problem. It happens when web socket generates a lot of messages that later get redirected to mqtt. It causes AsyncSocket message queue overflow. If some part the system generates identical messages we should not forward them.

This is not easy to solve. Why are your updates so frequent? I think the only way to get close to solving this issue reliably is with rate-limiting. I had implemented rate-limiting in the UI with lodash "throttle" as I prevously had similar overflows when the UI was sending rapid updates.

In this situation it was a user adjusting colors with a picker component or modifying brightness by dragging a slider that was causing the rapid updates.

See WebSocketController.tsx for this throttle example, we may be able implement similar rate limiting on the server side, but doing this is either lossy, or delays the messages. Choose your poison!

**Comment by kasedy** [comment]
Next time I will have separate branch for each feature.

Update the documentation. 

Every component of the system should contribute into traffic reduction by throttling update requests and preventing message duplication.

**Pull request closed without merging**
