### PR TITLE
Extend status

### PR DESCRIPTION
**Pull request by rjwats**

### CODE REVIEW

**Comment by rjwats** [comment]
This is an intersting one I looked at before. The calculation for sketch space % is a bit confusing. I think I'm understanding this right but please correct me if know otherwise.

The function ESP.getFreeSketchSpace() returns the amount of flash storage available for an OTA update:

- **ESP32**  Here there is a [standby partition](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#built-in-partition-tables) for the OTA sketch to be copied to during the update. In this case getFreeSketchSpace tells you the size of the standby partition which is invariabley the max supported sketch size as the two OTA partitions are the same size.
- **ESP8266** Here there is a [contiguious block of flash](http://arduino.esp8266.com/Arduino/versions/2.1.0-rc2/doc/ota_updates/ota_updates.html#updater-class) used for the sketch and the free space. In this case getFreeSketchSpace tells you the remaining size of this flash block. 

In the case of the esp8266, this calculation doesn't really work:

image
image

It does on the ESP32:

image
image

I couldn't think of a way to make this work - so I ditched it.

Other changes:

- Make the screen a bit more compact
- Introduce the flash chip speed, we have it in the payload so why not display it
- Transfer the max_alloc size instead of the ~ calculated fragmentation %. This way we can display both. I think the max_alloc size will probably be more useful for trying to debug problems.

On a worrying note, with the approximation calculation the ESP32 shows 44% fragmentation:

image

Yikes! I'd love to do a proper fragmentation calculation but I dont think it's possible to get detailed enough heap information from the API (unlike on the esp8266). I've not done a heap dump before but maybe it's time. It's undoutely not actually 44%, the approximation can be poor if it's just a few blocks occupied in the middle of the heap. [How to do it properly.](https://github.com/rhempel/umm_malloc/issues/14#issuecomment-571138523)

**Comment by kasedy** [comment]
Sketch size for esp8266 can not exceed 1MB even it has 4MB memory chip. Explanation is [here](https://arduino-esp8266.readthedocs.io/en/latest/faq/readme.html#in-the-ide-for-esp-12e-that-has-4m-flash-i-can-choose-4m-1m-fs-or-4m-3m-fs-no-matter-what-i-select-the-ide-tells-me-the-maximum-code-space-is-about-1m-where-does-my-flash-go). ESP.getFreeSketchSpace() function return the memory available between the beginning of flash and start of SPPIFFS. I didn't find a way how to extract "real" maximum sketch size. So I had an idea just to define it.

```
|--------------|-------|---------------|--|--|--|--|--|
^              ^       ^               ^     ^
Sketch    OTA update   SPIFFS  EEPROM  WiFi config (SDK)
```

**Comment by kasedy** [comment]
esp8266 SDK has ESP.getHeapFragmentation() that calculates it properly. I didn't find similar function for esp32.

**Comment by rjwats** [comment]
Yes, it looks like the heap stats arn't as detailed. I'll try a dump at some point.

**Pull request merged**
