### PR TITLE
 Use text formatting for default factory values to produce dynamic names.

### PR DESCRIPTION
**Pull request by kasedy**

### CODE REVIEW

**Comment by rjwats** [comment]
Sorry I've been neglecting this PR, been grapling with logging stuff (and work).

This looks like a more flexable approach to getting device ID into the factory settings. Certainly better than having code in the ini files. Probably even worth configuring the WiFi hostname to contain the device id by default.

I'd question if the SSID for station mode configuration (FACTORY_WIFI_SSID) could ever have a valid use case for the placeholders though - what's the thinking there?

Will look at getting this documented and back in shortly, thx :)

**Comment by kasedy** [comment]
Agree about FACTORY_WIFI_SSID. I did fixes and merged latest changes.

**Comment by kasedy** [comment]
Updated documentation

**Comment by rjwats** [comment]
Cool thx proddy. I'll look at pulling this in shortly.

**Pull request merged**
