### PR TITLE
Refactor stateful service to allow more control over updates

### PR DESCRIPTION
**Pull request by rjwats**

### CODE REVIEW

**Comment by rjwats** [comment]
@kasedy Thx for the recent PRs.

Stopping the AP from shutting down when there are clients connected is probably a good idea. I've spotted a bunch of other bugs in that area too (such as not being able to change the access point password/ssid while it's up and running). I'll get those fixed shortly.

I think the change in the PR is important. It statifies your requirement better than hobbling the Deserializer function. Let me know what you think when you get a sec.

**Comment by kasedy** [comment]
I'll review a bit later.

**Comment by kasedy** [comment]
I see multiple issues with this implementation. First of all the change assumes that T class must have copy constructor. Such constraint makes esp8266-react framework less flexible and extendable. I like more how it was before. It was very easy to fuse esp8266-react and core logic from my project. I had a core class that held state and controlled light. The migration was very simple. I placed the core class into StatefulService and implemented several endpoints. If you merge this changes it will be a disaster for my project. I will need to move core logic into StatefulService and rework whole project.

StatefulService class gets overloaded. On my opinion it should do only one thing. Track the change of _state_ and notify subscribers. Validation and state overwrite should happen in the other place.

I strongly believe serializer/deserializer should be a mediator between StatefulService and T that knows how to update T, track if it changed or if there were any validation issues.

Once again this change will make the framework less user friendly and harder to extend.

**Comment by rjwats** [comment]
The copy constructor constraint annoying, the assumption there is that T will be trivial data classes which may not be the case like you noted. I'm also not a fan of the override either.

I guess it's a case of, if your requirements don't fit the basic framework features you can always write your own code which uses the stateful service classes directly.

**Comment by kasedy** [comment]
How do you think what class should control the device? I mean change pin state / poll sensors / control external display / rotary encoder / buttons.

**Pull request closed without merging**
