### PR TITLE
Fixed crash due to uninitialized variable

### PR DESCRIPTION
**Pull request by kasedy**
Fixed crash.

### CODE REVIEW

**Comment by rjwats** [comment]
Looks like we might need to make this change in OTASettingsService too, _arduinoOTA is uninitialized there.

**Comment by kasedy** [comment]
Right, it is the second place.

**Comment by rjwats** [comment]
Out of interest, what steps induce the crash?

**Comment by kasedy** [comment]
Nothing special, just a piece of bad luck. 

It starts crashing on boot as I reformat the code. I create ESP8266React dynamically with new operator and have so called "Emergency Protocol" that works prior instancing ESP8266React.

Usually when program start all memory (heap+stack) filled with zeros. So you don't see the problem with an example code as it declares global instance of ESP8266React. It is the first object that program creates in a fresh memory. 

In my case ESP8266React reuses memory previously occupied by "Emergency Protocol". C++ delete operator marks a piece of memory as free but doesn't wipe it out. A a result uninitialized pointer get a random value.

**Comment by rjwats** [comment]
Your bottle project looks cool :)

I did something similar too for my christmas tree.

**Pull request merged**
