### PR TITLE
Add factory reset feature

### PR DESCRIPTION
**Pull request by kasedy**
1. Added factory reset feature that:
  a. Reset all configuration settings
  b. Reset wifi settings
  c. Reboots the device to apply the changes
2. Default config values can be provided as macro compile flags. It is an easy way to customize default settings. See config_default_settings.ini in examples.
3. Removed default config json files as they were replaced with macros variables. If config/***.json file is missed from SPIFFS, FSPersistence will create it from default values provided through macro definitions.
4. Added reset button and confirmation dialog to System page

### CODE REVIEW

**Comment by rjwats** [comment]
This looks like a decent change thx. I'll merge it into a feature branch and update the docs and maybe re-word some of the UI.

**Comment by kasedy** [comment]
Thank you. Feel free to change.

**Comment by proddy** [comment]
I thought to have the settings in files separate from the core library was a good thing. If all the defaults are now deeply embedded into the lib/framework individual header files anyone wanting to use the framework has to change many files, and re-do their changes when the next release comes out.

**Comment by proddy** [comment]
oh forget that last comment. I see what you did there. Using #defines to override the defaults.

**Comment by kasedy** [comment]
I thought about moving all macros variables that store default config values into a septet file and rename to have identical pattern:

CONFIG_DEFAULT_SETTINGS_*MODULE*_*PROPERTY_NAME*

**Comment by rjwats** [comment]
Was the 200ms sleep required to get this working or was that a "just in case" thing?

**Comment by kasedy** [comment]
It gives wifi time to switch off and erase stored ssid and password. It is copied from my past well-tested project.

**Pull request merged**
