### PR TITLE
Settings placeholder substitution

### PR DESCRIPTION
**Pull request by rjwats**
Hey @kasedy,

Thx for this, nice little change. The templates weren't working for me as PlatformIO was expanding them to empty strings before handing them off to the build process. I couldn't even get it working by escaping the dollars - strange. Removing the dollar from our placeholders trick though, look OK?

I opted to restore the settings ifndefs. IMO it's nice to have the source code build without any external defines needing to be provided (especially useful if you want to produce a project from the source code which won't be built with PIO).

Just finishing off testing this under various *nix configurations.

### CODE REVIEW

**Comment by kasedy** [comment]
We can replace dollar sign ($) with a hash (#) to avoid bash variable expansion.

**Comment by rjwats** [comment]
Updated to use #{value} seems to work

**Comment by rjwats** [comment]
Have been struggling with odd issues while testing this branch on one of my ESP8266 devices (a nodemcuv2 board). 

It was exhibiting an unresponsive access point when erasing flash before uploading (effectively a factory reset). Oddly the culprit appears to be the use of flash string helpers and the following change solves the issue (my older nodemcuv0.9 board works fine without this change):

image

I'm not entirely sure why it solves the problem and would love to know if anyone is more enlightened.

**Comment by proddy** [comment]
I'm facing a similar problem, `esptool.py erase_flash` -> upload firmware brings up an empty Captive Portal page. I'll try the workaround.

**Comment by rjwats** [comment]
Thanks, it would be good to know it's not just my device.

**Comment by proddy** [comment]
Haven't been able to reproduce it unfortunately. I'm back on master now.

**Comment by kasedy** [comment]
Do we plan to merge this feature into main?

**Comment by rjwats** [comment]
Think so, it's seemed like a sensible change. IIRC last time I looked at
this I had a strange issue with it on one off my esp8266 devices. I
couldn't see how it was related to the change, perhaps a dodgy flash chip
on that particular device. I'll have another look this eve.

**Comment by rjwats** [comment]
I couldn't re-create the issue I saw last time around so this is probs OK to merge. Have caught it up with master and applied the fix from before for good measure. Have run out of time tonight.. will review the code and merge this tomorrow

**Comment by kasedy** [comment]
I also had this issue in the past. It is not related with the change. I believe the issue is in esp8266-Arduino SDK as it has lots of open tickets. For a long time I used ESPAsyncWiFiManager as it is the most issue free WiFi manager for ESP8266. It has many  workarounds to make WiFi work properly. For example it resets wifi before connecting to it [1]. Also it disconnects wifi on reset [2]. I think we should do something similar. By the way I skimmed the other projects. JustWifi and Tasmota have a workaround for WiFi connectivity issue [3] and [4].

[1] https://github.com/alanswx/ESPAsyncWiFiManager/blob/master/ESPAsyncWiFiManager.cpp#L575
[2] https://github.com/alanswx/ESPAsyncWiFiManager/blob/master/ESPAsyncWiFiManager.cpp#L691
[3] https://github.com/xoseperez/justwifi/blob/master/src/JustWifi.cpp#L65
[4] https://github.com/arendst/Tasmota/blob/development/tasmota/support_wifi.ino#L121

**Comment by rjwats** [comment]
Just need to replace "chipId" with "salt" to secure the JWT secret properly. It's a pretty significant security hole as it stands. I'm sure I can get PIO to generate a random value for a salt at build time... will look this eve.

**Comment by rjwats** [comment]
I think this might be ready now, another user of the framework spotted an issue with using efuse/chipId for the hostname which this PR also resolves:

https://github.com/rjwats/esp8266-react/issues/212

In addition I have resolved a security issue, where the default JWT secret was previously derived from the station MAC address which may be sniffed from the WiFi network (not great if you care about security!)

Thankfully the Arduino random() function was adapted for these devices to use the built-in hardware true random number generator so it offers a good solution for the default JWT secret (with added bonus that it's random rather than derrived and is re-generated on factory reset). Nice.

**Pull request merged**
