### PR TITLE
[WIP] Feat esp status

### PR DESCRIPTION
**Pull request by pcniatic**
Hey @rjwats , I have been working on a new functionality thats shows in the webpage some internal metrics/information like: _platform_, _cycle count_, _heap size_, etc...
Is already implemented for esp8266 and esp32, showing different metrics/information for both of them.
Right now is **work in progress**.

Screen Shot 2019-04-28 at 11 23 21 PM

**What do you think?**

### CODE REVIEW

**Comment by rjwats** [comment]
A reasonable feature to introduce and I would consider introducing the restart device feature in a release as part of this too.

It would make sense to me to have this in a "Device" (or "System") section, split up so it's not too overwhelming for UX reasons. With say: "Status", "Memory" and "Restart" tabs.

In the spirit of "less is more" I would personally omit cycle count ("uptime" already on the NTP Status page) and MAC address (MAC address now available on the WiFi Status page).

I would also consider returning a numerical restart code rather than the string version. This way users can customise the interface to their language, if they choose. You can get this from getResetInfoPtr() with constants/NTPStatus.js showing how I have dealt with mapping these to display values in the interface.

I have created a "ft_device_status" branch for you to open this PR when you are ready, this way we can collaborate until it's ready to go into master.

**Comment by pcniatic** [comment]
Great, I'll start working on a mockup prior to start developing.

**Comment by rjwats** [comment]
Hi @pcniatic,

I rolled some of your changes up into the latest release, there is now a "System" section in the UI where this stuff can live. I elected to go for a minimal set of information to start with. Thanks for this!

Rick

**Comment by pcniatic** [comment]
👍

**Pull request closed without merging**
