### PR TITLE
Factory reset feature

### PR DESCRIPTION
**Pull request by rjwats**

### CODE REVIEW

**Comment by rjwats** [comment]
@kasedy Making some changes here, comment here if you want.

**Comment by kasedy** [comment]
LGTM

**Comment by rjwats** [comment]
The deletion wasn't working for me on ESP32, works with an iterative approach. Did you manage to get rmDir working on your ESP32?

Removed the delay and the WiFi.disconnect() and as ESP.restart() should be graceful(ish) seems to work file without those calls (in my testing anyway) let me notice anything to the contrary.

Also fixed some wrapping issues in the UI on smaller screen sizes and shortened some of the messages. I think the big red button is enough of a warning :)

This is a decent addition thanks for the help. I'll document it tomorrow then look at merging after a bit more testing.

**Comment by kasedy** [comment]
I tested the changes only with esp8266. My esp32 will come next week.

**Pull request merged**
